export type SlotItem = {
  name: string;
  provider: string;
  image?: string;
};

export const slotData: SlotItem[] = [
// 3 Oaks
{ name: "Black Wolf", provider: "3 Oaks" },
{ name: "Coin Princess x1000", provider: "3 Oaks" },
{ name: "777 Fruity Coins", provider: "3 Oaks" },
{ name: "Sun of Egypt", provider: "3 Oaks" },
{ name: "Magic Apple 2", provider: "3 Oaks" },
{ name: "Coin UP: Lightning", provider: "3 Oaks" },
{ name: "Fortune Globe", provider: "3 Oaks" },
{ name: "Lucky Penny 2", provider: "3 Oaks" },
{ name: "Book of Sun Multichance", provider: "3 Oaks" },
{ name: "Chili Coins", provider: "3 Oaks" },
{ name: "Rio Gems", provider: "3 Oaks" },
{ name: "Lucky Penny", provider: "3 Oaks" },
{ name: "Power Sun XXL", provider: "3 Oaks" },
{ name: "Lava Coins", provider: "3 Oaks" },
{ name: "Coin Lamp", provider: "3 Oaks" },
{ name: "Aztec Fire", provider: "3 Oaks" },
{ name: "3 China Pots", provider: "3 Oaks" },
{ name: "Moon Sisters", provider: "3 Oaks" },
{ name: "Crystal Scarabs", provider: "3 Oaks" },
{ name: "Super Marble", provider: "3 Oaks" },
{ name: "Coin Volcano 2", provider: "3 Oaks" },
{ name: "Black Wolf 2", provider: "3 Oaks" },
{ name: "Sticky Piggy", provider: "3 Oaks" },
{ name: "Queen of the Sun", provider: "3 Oaks" },
{ name: "Lady Fortune", provider: "3 Oaks" },
{ name: "Aztec Fire 2", provider: "3 Oaks" },
{ name: "3 Aztec Temples", provider: "3 Oaks" },
{ name: "Tiger Gems", provider: "3 Oaks" },
{ name: "China Festival", provider: "3 Oaks" },
{ name: "Super China Pots", provider: "3 Oaks" },
{ name: "Wolf Saga", provider: "3 Oaks" },
{ name: "Must Drop Jackpot Hot Fire Fruits", provider: "3 Oaks" },
{ name: "Super Rich God: Hold and Win", provider: "3 Oaks" },
{ name: "Grab the Gold!", provider: "3 Oaks" },
{ name: "Dragon Pearls", provider: "3 Oaks" },
{ name: "Hot Fire Fruits", provider: "3 Oaks" },
{ name: "Grab more Gold!", provider: "3 Oaks" },
{ name: "Egypt Fire 2", provider: "3 Oaks" },
{ name: "Magic Clovers", provider: "3 Oaks" },
{ name: "Coin Express", provider: "3 Oaks" },
{ name: "Book of Sun: Choice", provider: "3 Oaks" },
{ name: "Dragon Wealth", provider: "3 Oaks" },
{ name: "Super Hot Teapots", provider: "3 Oaks" },
{ name: "3 Clover Pots Extra", provider: "3 Oaks" },
{ name: "Scarab Riches", provider: "3 Oaks" },
{ name: "Egypt Fire", provider: "3 Oaks" },
{ name: "Scarab Temple", provider: "3 Oaks" },
{ name: "Gold Nuggets", provider: "3 Oaks" },
{ name: "Hit more Gold!", provider: "3 Oaks" },
{ name: "4 Fairy Flowers", provider: "3 Oaks" },
{ name: "Sun of Egypt 2", provider: "3 Oaks" },
{ name: "3 Egypt Chests", provider: "3 Oaks" },
{ name: "More Magic Apple", provider: "3 Oaks" },
{ name: "3 Olymp Fortunes", provider: "3 Oaks" },
{ name: "Amazonia Wins", provider: "3 Oaks" },
{ name: "Little Farm", provider: "3 Oaks" },
{ name: "Maya Lock", provider: "3 Oaks" },
{ name: "Super Hot Chilli", provider: "3 Oaks" },
{ name: "3 Pots of Egypt", provider: "3 Oaks" },
{ name: "777 Coins", provider: "3 Oaks" },
{ name: "Power Sun", provider: "3 Oaks" },
{ name: "Green Chilli 2", provider: "3 Oaks" },
{ name: "777 Gems ReSpin", provider: "3 Oaks" },
{ name: "Sky Pearls", provider: "3 Oaks" },
{ name: "Magic Apple", provider: "3 Oaks" },
{ name: "3 Clover Pots", provider: "3 Oaks" },
{ name: "Gold Express", provider: "3 Oaks" },
{ name: "3 Coins", provider: "3 Oaks" },
{ name: "3 Hot Chillies", provider: "3 Oaks" },
{ name: "Lion Coins", provider: "3 Oaks" },
{ name: "Big Heist", provider: "3 Oaks" },
{ name: "Dancing Joker", provider: "3 Oaks" },
{ name: "DJ Tiger x1000", provider: "3 Oaks" },
{ name: "Tiger Jungle", provider: "3 Oaks" },
{ name: "Lord of Thunder", provider: "3 Oaks" },
{ name: "Aztec Sun", provider: "3 Oaks" },
{ name: "Rush for Gold", provider: "3 Oaks" },
{ name: "Sunlight Princess", provider: "3 Oaks" },
{ name: "Super Sticky Piggy", provider: "3 Oaks" },
{ name: "Wolf Night", provider: "3 Oaks" },
{ name: "Egypt Power x1000", provider: "3 Oaks" },
{ name: "Buddha Megaways", provider: "3 Oaks" },
{ name: "Golden Teapot", provider: "3 Oaks" },
{ name: "Boom! Boom! Gold!", provider: "3 Oaks" },
{ name: "3 Coin Volcanoes", provider: "3 Oaks" },
{ name: "15 Dragon Pearls", provider: "3 Oaks" },
{ name: "3 Super Hot Chillies", provider: "3 Oaks" },
{ name: "Coin Volcano", provider: "3 Oaks" },
{ name: "3 Super Coin Volcanoes", provider: "3 Oaks" },
{ name: "Fishin' Bear", provider: "3 Oaks" },
{ name: "Space Coins", provider: "3 Oaks" },
{ name: "3 African Drums", provider: "3 Oaks" },
{ name: "Hit the Gold!", provider: "3 Oaks" },
{ name: "4 Pots of Egypt", provider: "3 Oaks" },
{ name: "3 Hot Teapots", provider: "3 Oaks" },
{ name: "Lava Coins 2", provider: "3 Oaks" },
{ name: "4 Wolf Drums", provider: "3 Oaks" },
{ name: "3 Jewel Crowns", provider: "3 Oaks" },
{ name: "Green Chilli", provider: "3 Oaks" },

// AvatarUX
{ name: "Animals Strike", provider: "AvatarUX" },
{ name: "Crypto Bro", provider: "AvatarUX" },
{ name: "Fruitillionaire", provider: "AvatarUX" },
{ name: "3 Power Genies", provider: "AvatarUX" },
{ name: "Big Catch Craze", provider: "AvatarUX" },
{ name: "Piggy Pop", provider: "AvatarUX" },
{ name: "Beastly Burglars", provider: "AvatarUX" },
{ name: "Duck Hunt 500", provider: "AvatarUX" },
{ name: "Spinfection", provider: "AvatarUX" },
{ name: "Monkey Pop", provider: "AvatarUX" },
{ name: "POP O'Gold", provider: "AvatarUX" },
{ name: "Coyote Gold", provider: "AvatarUX" },
{ name: "Rebel Paws", provider: "AvatarUX" },
{ name: "Silicon Spinners", provider: "AvatarUX" },
{ name: "Worms of Valor", provider: "AvatarUX" },
{ name: "Imperial Coins", provider: "AvatarUX" },
{ name: "80sPop", provider: "AvatarUX" },
{ name: "Sweet Gummy", provider: "AvatarUX" },
{ name: "AstroPop", provider: "AvatarUX" },
{ name: "Spinxiety", provider: "AvatarUX" },
{ name: "Cherry Pop", provider: "AvatarUX" },
{ name: "Reel Warriors", provider: "AvatarUX" },
{ name: "ArcanaPop", provider: "AvatarUX" },
{ name: "Bounty Pop", provider: "AvatarUX" },
{ name: "Critter Pop", provider: "AvatarUX" },
{ name: "Electric Rush", provider: "AvatarUX" },
{ name: "Midnight Hunt", provider: "AvatarUX" },
{ name: "The Vault Chase", provider: "AvatarUX" },
{ name: "Captain More'gain", provider: "AvatarUX" },
{ name: "KokeshiPop", provider: "AvatarUX" },
{ name: "LooneyPop", provider: "AvatarUX" },
{ name: "Lolli Pop", provider: "AvatarUX" },
{ name: "Tiki Pop", provider: "AvatarUX" },
{ name: "Vegas Fortune", provider: "AvatarUX" },
{ name: "Raging Pop", provider: "AvatarUX" },
{ name: "JinglePop", provider: "AvatarUX" },
{ name: "Hippo Pop", provider: "AvatarUX" },
{ name: "HipHopPop", provider: "AvatarUX" },
{ name: "Wild Pops", provider: "AvatarUX" },
{ name: "Canyon Riches", provider: "AvatarUX" },
{ name: "CherryPop Burst", provider: "AvatarUX" },
{ name: "MonkeyPop 2", provider: "AvatarUX" },
{ name: "Cherry Pop Deluxe", provider: "AvatarUX" },
{ name: "Pop Noir", provider: "AvatarUX" },
{ name: "HelioPOPolis", provider: "AvatarUX" },
{ name: "TikiPop Spooky Temples", provider: "AvatarUX" },
{ name: "GemPops", provider: "AvatarUX" },
{ name: "Diamond Dez", provider: "AvatarUX" },
{ name: "Electro Cubes", provider: "AvatarUX" },
{ name: "Juicy Pop", provider: "AvatarUX" },
{ name: "Cosmic Jokers", provider: "AvatarUX" },
{ name: "Sphinx Treasure", provider: "AvatarUX" },
{ name: "Witchy POPpins", provider: "AvatarUX" },
{ name: "PixiePOP", provider: "AvatarUX" },
{ name: "Big Catch Xmas", provider: "AvatarUX" },
{ name: "Gods Gone Wild", provider: "AvatarUX" },
{ name: "ReefPop", provider: "AvatarUX" },
{ name: "Pop Rocks", provider: "AvatarUX" },
{ name: "XmasPop Delight", provider: "AvatarUX" },
{ name: "Depths of Fortune", provider: "AvatarUX" },
{ name: "Pixel Paws", provider: "AvatarUX" },
{ name: "PiggyPop Grand Affair", provider: "AvatarUX" },
{ name: "Papaya Pop", provider: "AvatarUX" },
{ name: "Zombie aPOPalypse", provider: "AvatarUX" },
{ name: "Kitty POPpins", provider: "AvatarUX" },

// Bullshark (FINAL - VERIFIED)
{ name: "Age of Seth", provider: "Bullshark" },
{ name: "Astro Rumble", provider: "Bullshark" },
{ name: "Belle the Blade Hunter", provider: "Bullshark" },
{ name: "Ancient Paws", provider: "Bullshark" },
{ name: "Culinary Clash", provider: "Bullshark" },
{ name: "Junkyard Kings", provider: "Bullshark" },
{ name: "Wild Dojo Strike", provider: "Bullshark" },
{ name: "Godly Gains", provider: "Bullshark" },
{ name: "Bullride Loot", provider: "Bullshark" },
{ name: "Paper Biker", provider: "Bullshark" },
{ name: "Amazing Miceketeers", provider: "Bullshark" },
{ name: "Clover Club", provider: "Bullshark" },
{ name: "Charm of the Dragon", provider: "Bullshark" },
{ name: "Valhalla: Wild Winter", provider: "Bullshark" },
{ name: "Pickle Bandits", provider: "Bullshark" },
{ name: "Coop Clash", provider: "Bullshark" },
{ name: "Empress of The Shadows", provider: "Bullshark" },
{ name: "Fury and Fortune", provider: "Bullshark" },
{ name: "Holy Heist", provider: "Bullshark" },
{ name: "Merlin's Mania", provider: "Bullshark" },
{ name: "Jawsome Pirates", provider: "Bullshark" },
{ name: "Grunt Gold", provider: "Bullshark" },
{ name: "Gem Ghosts", provider: "Bullshark" },

// Backseat Gaming
{ name: "Banana Farm", provider: "Backseat Gaming" },
{ name: "Barrel Bonanza", provider: "Backseat Gaming" },
{ name: "Power Pops", provider: "Backseat Gaming" },
{ name: "Blaze Buddies", provider: "Backseat Gaming" },
{ name: "Pirate Bonanza", provider: "Backseat Gaming" },
{ name: "Clumsy Cowboys", provider: "Backseat Gaming" },
{ name: "Crystal Robot", provider: "Backseat Gaming" },
{ name: "Old Gun", provider: "Backseat Gaming" },
{ name: "Hoot Shot The Sheriff", provider: "Backseat Gaming" },
{ name: "Pirate Bonanza 2", provider: "Backseat Gaming" },
{ name: "Chocolate Rocket", provider: "Backseat Gaming" },
{ name: "Super Twins", provider: "Backseat Gaming" },
{ name: "Mystery Bats", provider: "Backseat Gaming" },
{ name: "Shadow Strike", provider: "Backseat Gaming" },
{ name: "Pyrofox", provider: "Backseat Gaming" },
{ name: "Chicken Man", provider: "Backseat Gaming" },
{ name: "Infernus", provider: "Backseat Gaming" },
{ name: "Home of Thor", provider: "Backseat Gaming" },
{ name: "Desert Temple", provider: "Backseat Gaming" },
{ name: "Sleepy Grandpa", provider: "Backseat Gaming" },
{ name: "Fireborn", provider: "Backseat Gaming" },
{ name: "Blade Master", provider: "Backseat Gaming" },
{ name: "Space Zoo", provider: "Backseat Gaming" },
{ name: "Neon Frames", provider: "Backseat Gaming" },
{ name: "Gladius: Death Or Glory", provider: "Backseat Gaming" },
{ name: "Halls of Odin", provider: "Backseat Gaming" },
{ name: "Commander of Tridents", provider: "Backseat Gaming" },
{ name: "The Cursed King", provider: "Backseat Gaming" },
{ name: "Lord Venom", provider: "Backseat Gaming" },

// Clawbuster
{ name: "3 Claws of Aztec Fire: Hold & Win", provider: "Clawbuster" },
{ name: "Asgard Bonanza: Gods Claw", provider: "Clawbuster" },
{ name: "Clawbass Bonanza 2000", provider: "Clawbuster" },
{ name: "Guns of Gold", provider: "Clawbuster" },
{ name: "Buffalo Power Claw: Hold and Win", provider: "Clawbuster" },
{ name: "Sweet Dream Bonanza Claw 2000", provider: "Clawbuster" },
{ name: "3 Claws of Fortune", provider: "Clawbuster" },
{ name: "Frozen Vault: Hold&Win", provider: "Clawbuster" },
{ name: "Panda Claw Jackpot", provider: "Clawbuster" },
{ name: "The Great Clawsby Deluxe: Hold and Win", provider: "Clawbuster" },
{ name: "Catch the Wild Claw", provider: "Clawbuster" },
{ name: "Crazy Crazy Claw", provider: "Clawbuster" },
{ name: "Fruits OR Gems Clawctail", provider: "Clawbuster" },
{ name: "Zeus VS Thanatos Claw", provider: "Clawbuster" },
{ name: "Claw Bonanza: Gold Rush", provider: "Clawbuster" },
{ name: "Joker, Fruits & Claw", provider: "Clawbuster" },
{ name: "Hot Lucky Sevens Claw", provider: "Clawbuster" },
{ name: "Fruits, Coins & Claw", provider: "Clawbuster" },
{ name: "Double Triple Burning Wilds", provider: "Clawbuster" },
{ name: "Double Triple Wild Claw", provider: "Clawbuster" },
{ name: "Hell or Win Claw: Hold & Win", provider: "Clawbuster" },
{ name: "Rainbow Bonanza", provider: "Clawbuster" },
{ name: "Juicy Claw", provider: "Clawbuster" },
{ name: "Lucky Scarab Claw: Wild Respins", provider: "Clawbuster" },
{ name: "Book Of Claws", provider: "Clawbuster" },
{ name: "Gems Claw Xtreme", provider: "Clawbuster" },
{ name: "Zeus Claws", provider: "Clawbuster" },
{ name: "Book of Fortune Clover", provider: "Clawbuster" },
{ name: "ClawBass Bonanza", provider: "Clawbuster" },
{ name: "Aztec Clawways", provider: "Clawbuster" },

// Hacksaw (slots only – no scratch / table games)
{ name: "Wanted Dead or a Wild", provider: "Hacksaw" },
{ name: "Le Fisherman", provider: "Hacksaw" },
{ name: "Miami Mayhem", provider: "Hacksaw" },
{ name: "Le Pharaoh", provider: "Hacksaw" },
{ name: "Fist of Destruction", provider: "Hacksaw" },
{ name: "Ze Zeus", provider: "Hacksaw" },
{ name: "Le King", provider: "Hacksaw" },
{ name: "The Luxe", provider: "Hacksaw" },
{ name: "Le Viking", provider: "Hacksaw" },
{ name: "Chaos Crew 2", provider: "Hacksaw" },
{ name: "Le Bandit", provider: "Hacksaw" },
{ name: "Danny Dollar", provider: "Hacksaw" },
{ name: "Donny Dough", provider: "Hacksaw" },
{ name: "Slayers Inc", provider: "Hacksaw" },
{ name: "Toshi Ways Club", provider: "Hacksaw" },
{ name: "SixSixSix", provider: "Hacksaw" },
{ name: "FRKN Bananas", provider: "Hacksaw" },
{ name: "Xmas Drop", provider: "Hacksaw" },
{ name: "Cloud Princess", provider: "Hacksaw" },
{ name: "Duel at Dawn", provider: "Hacksaw" },
{ name: "Jaws of Justice", provider: "Hacksaw" },
{ name: "2 Wild 2 Die", provider: "Hacksaw" },
{ name: "Pray For Six", provider: "Hacksaw" },
{ name: "Densho", provider: "Hacksaw" },
{ name: "Sun Princess", provider: "Hacksaw" },
{ name: "Le Santa", provider: "Hacksaw" },
{ name: "Life and Death", provider: "Hacksaw" },
{ name: "RIP City", provider: "Hacksaw" },
{ name: "Le Cowboy", provider: "Hacksaw" },
{ name: "Army of Ares", provider: "Hacksaw" },
{ name: "Chaos Crew 3", provider: "Hacksaw" },
{ name: "Bash Bros", provider: "Hacksaw" },
{ name: "Fighter Pit", provider: "Hacksaw" },
{ name: "Octo Attack", provider: "Hacksaw" },
{ name: "Stormforged", provider: "Hacksaw" },
{ name: "Aiko and the Wind Spirit", provider: "Hacksaw" },
{ name: "Circle of Life", provider: "Hacksaw" },
{ name: "Cursed Seas", provider: "Hacksaw" },
{ name: "The Luxe H.V.", provider: "Hacksaw" },
{ name: "Spinman", provider: "Hacksaw" },
{ name: "Dorks of the Deep", provider: "Hacksaw" },
{ name: "Mayan Stackways", provider: "Hacksaw" },
{ name: "Rotten", provider: "Hacksaw" },
{ name: "Hand of Anubis", provider: "Hacksaw" },
{ name: "Dork Unit", provider: "Hacksaw" },
{ name: "Donny and Danny", provider: "Hacksaw" },
{ name: "Zeus Ze Zecond", provider: "Hacksaw" },
{ name: "Beast Below", provider: "Hacksaw" },
{ name: "Le Zeus", provider: "Hacksaw" },
{ name: "Magic Piggy", provider: "Hacksaw" },
{ name: "Stack 'Em", provider: "Hacksaw" },
{ name: "Hot Ross", provider: "Hacksaw" },
{ name: "Invictus", provider: "Hacksaw" },
{ name: "Book of Time", provider: "Hacksaw" },
{ name: "Drop'em", provider: "Hacksaw" },
{ name: "Benny the Beer", provider: "Hacksaw" },
{ name: "Shaolin Master", provider: "Hacksaw" },
{ name: "Spear of Athena", provider: "Hacksaw" },
{ name: "Eye of the Panda", provider: "Hacksaw" },
{ name: "Gronk's Gems", provider: "Hacksaw" },
{ name: "Immortal Desire", provider: "Hacksaw" },
{ name: "Marlin Masters", provider: "Hacksaw" },
{ name: "Stormborn", provider: "Hacksaw" },
{ name: "Smoking Dragon", provider: "Hacksaw" },
{ name: "Fire my Laser", provider: "Hacksaw" },
{ name: "Rainbow Princess", provider: "Hacksaw" },
{ name: "Spinman H.V.", provider: "Hacksaw" },
{ name: "Deal With Death", provider: "Hacksaw" },
{ name: "Double Rainbow", provider: "Hacksaw" },
{ name: "Bullets and Bounty", provider: "Hacksaw" },
{ name: "Joker Bombs", provider: "Hacksaw" },
{ name: "Evil Eyes", provider: "Hacksaw" },
{ name: "Donut Division", provider: "Hacksaw" },
{ name: "Ultimate Slot of America", provider: "Hacksaw" },
{ name: "Dragon's Domain", provider: "Hacksaw" },
{ name: "Divine Drop", provider: "Hacksaw" },
{ name: "Pray for Three", provider: "Hacksaw" },
{ name: "The Count", provider: "Hacksaw" },
{ name: "Tai the Toad", provider: "Hacksaw" },
{ name: "Chaos Crew", provider: "Hacksaw" },
{ name: "Cursed Crypt", provider: "Hacksaw" },
{ name: "Beam Boys", provider: "Hacksaw" },
{ name: "Pug Life", provider: "Hacksaw" },
{ name: "Frank's Farm", provider: "Hacksaw" },
{ name: "Temple of Torment", provider: "Hacksaw" },
{ name: "Ronin Stackways", provider: "Hacksaw" },
{ name: "Hounds of Hell", provider: "Hacksaw" },
{ name: "Rad Maxx", provider: "Hacksaw" },
{ name: "Reign of Rome", provider: "Hacksaw" },
{ name: "Steamrunners", provider: "Hacksaw" },
{ name: "Fred's Food Truck", provider: "Hacksaw" },
{ name: "Born Wild", provider: "Hacksaw" },
{ name: "Eye of Medusa", provider: "Hacksaw" },
{ name: "Wings of Horus", provider: "Hacksaw" },
{ name: "Toshi Video Club", provider: "Hacksaw" },
{ name: "Rise of Ymir", provider: "Hacksaw" },
{ name: "Keep'em", provider: "Hacksaw" },
{ name: "Dawn of Kings", provider: "Hacksaw" },
{ name: "Fear The Dark", provider: "Hacksaw" },
{ name: "Bouncy Bombs", provider: "Hacksaw" },
{ name: "Dark Spiral", provider: "Hacksaw" },
{ name: "Strength of Hercules", provider: "Hacksaw" },
{ name: "Dark Summoning", provider: "Hacksaw" },
{ name: "Booze Bash", provider: "Hacksaw" },
{ name: "ITERO", provider: "Hacksaw" },
{ name: "Phoenix DuelReels", provider: "Hacksaw" },
{ name: "Outlaws Inc", provider: "Hacksaw" },
{ name: "Vending Machine", provider: "Hacksaw" },
{ name: "Cash Crew", provider: "Hacksaw" },
{ name: "Alpha Eagle", provider: "Hacksaw" },
{ name: "Speed Crash", provider: "Hacksaw" },
{ name: "The Wildwood Curse", provider: "Hacksaw" },
{ name: "Snow Slingers", provider: "Hacksaw" },
{ name: "Gladiator Legends", provider: "Hacksaw" },
{ name: "Buffalo Stack'n'Sync", provider: "Hacksaw" },
{ name: "Time Spinners", provider: "Hacksaw" },
{ name: "Marlin Masters: The Big Haul", provider: "Hacksaw" },
{ name: "Undead Fortune", provider: "Hacksaw" },
{ name: "Stick 'Em", provider: "Hacksaw" },
{ name: "Cash Compass", provider: "Hacksaw" },
{ name: "Aztec Twist", provider: "Hacksaw" },
{ name: "Feel The Beat", provider: "Hacksaw" },
{ name: "Jelly Slice", provider: "Hacksaw" },
{ name: "King Carrot", provider: "Hacksaw" },
{ name: "Fruit Duel", provider: "Hacksaw" },
{ name: "Rocket Reels", provider: "Hacksaw" },
{ name: "Twisted Lab", provider: "Hacksaw" },
{ name: "Get the CHEESE", provider: "Hacksaw" },
{ name: "Mystery Motel", provider: "Hacksaw" },
{ name: "Klowns", provider: "Hacksaw" },
{ name: "Cubes 2", provider: "Hacksaw" },
{ name: "Keep'em Cool", provider: "Hacksaw" },
{ name: "OmNom", provider: "Hacksaw" },
{ name: "Rusty & Curly", provider: "Hacksaw" },
{ name: "Wishbringer", provider: "Hacksaw" },
{ name: "Balloons", provider: "Hacksaw" },
{ name: "Forest Fortune", provider: "Hacksaw" },
{ name: "Blocks", provider: "Hacksaw" },
{ name: "Bloodthirst", provider: "Hacksaw" },
{ name: "Harvest Wilds", provider: "Hacksaw" },
{ name: "3 Arcane Cauldrons", provider: "Hacksaw" },
{ name: "Rat Riches", provider: "Hacksaw" },
{ name: "Sugar Park", provider: "Hacksaw" },
{ name: "Through the Fire", provider: "Hacksaw" },
{ name: "Cash Quest", provider: "Hacksaw" },
{ name: "Epic Bullets & Bounty", provider: "Hacksaw" },
{ name: "Forbidden Fury", provider: "Hacksaw" },
{ name: "Let it Snow", provider: "Hacksaw" },
{ name: "8-Bit Quest", provider: "Hacksaw" },
{ name: "Le Bunny", provider: "Hacksaw" },
{ name: "Mighty Masks", provider: "Hacksaw" },
{ name: "Shadow Treasure", provider: "Hacksaw" },
{ name: "Tasty Treats", provider: "Hacksaw" },
{ name: "Alchemist Wonders", provider: "Hacksaw" },
{ name: "The Respinners", provider: "Hacksaw" },
{ name: "Hop'n'Pop", provider: "Hacksaw" },
{ name: "Penguin Royale", provider: "Hacksaw" },
{ name: "Warrior Ways", provider: "Hacksaw" },
{ name: "Orb of Destiny", provider: "Hacksaw" },
{ name: "Colors", provider: "Hacksaw" },
{ name: "Eternal Duel", provider: "Hacksaw" },
{ name: "Xpander", provider: "Hacksaw" },
{ name: "Miami Multiplier", provider: "Hacksaw" },
{ name: "Street Knockout", provider: "Hacksaw" },
{ name: "Boxes", provider: "Hacksaw" },
{ name: "Cubes", provider: "Hacksaw" },
{ name: "Lines", provider: "Hacksaw" },
{ name: "Wheel", provider: "Hacksaw" },
{ name: "Tiger Legends", provider: "Hacksaw" },

// Peter & Sons
{ name: "The Mafiosi", provider: "Peter & Sons" },
{ name: "Thunderhawk", provider: "Peter & Sons" },
{ name: "Dungeon Tower", provider: "Peter & Sons" },
{ name: "Epic Hellas", provider: "Peter & Sons" },
{ name: "Wild Bard", provider: "Peter & Sons" },
{ name: "Wild Duel", provider: "Peter & Sons" },
{ name: "Gunpowder", provider: "Peter & Sons" },
{ name: "Wild One", provider: "Peter & Sons" },
{ name: "Dragon Blox", provider: "Peter & Sons" },
{ name: "Steamworks - The Workshop", provider: "Peter & Sons" },
{ name: "Potion Power", provider: "Peter & Sons" },
{ name: "Barbarossa", provider: "Peter & Sons" },
{ name: "Ghost Father", provider: "Peter & Sons" },
{ name: "Precious 7", provider: "Peter & Sons" },
{ name: "Animafia", provider: "Peter & Sons" },
{ name: "Zombie Road", provider: "Peter & Sons" },
{ name: "Barbarossa Revenge", provider: "Peter & Sons" },
{ name: "Coin Blox", provider: "Peter & Sons" },
{ name: "Robin - Nottingham Raiders", provider: "Peter & Sons" },
{ name: "Gnomes & Giants", provider: "Peter & Sons" },
{ name: "Punch Club", provider: "Peter & Sons" },
{ name: "Valkyries", provider: "Peter & Sons" },
{ name: "Greedy Alice", provider: "Peter & Sons" },
{ name: "Evil Devil", provider: "Peter & Sons" },
{ name: "Xibalba", provider: "Peter & Sons" },
{ name: "Peter Hunter", provider: "Peter & Sons" },
{ name: "Cauldron", provider: "Peter & Sons" },
{ name: "Ghostfather Awakened", provider: "Peter & Sons" },
{ name: "Water Blox", provider: "Peter & Sons" },
{ name: "Sands of Destiny", provider: "Peter & Sons" },
{ name: "Voodoo Hex", provider: "Peter & Sons" },
{ name: "Rust World", provider: "Peter & Sons" },
{ name: "Frozen Age", provider: "Peter & Sons" },
{ name: "Artifacts", provider: "Peter & Sons" },
{ name: "Steamworks - Gears of Fortune", provider: "Peter & Sons" },
{ name: "Robin - Sherwood Marauders", provider: "Peter & Sons" },
{ name: "Abrakadabra", provider: "Peter & Sons" },
{ name: "Hammer of Gods", provider: "Peter & Sons" },
{ name: "Alibi", provider: "Peter & Sons" },
{ name: "Dig It", provider: "Peter & Sons" },
{ name: "Mutagenes", provider: "Peter & Sons" },
{ name: "Johnan Legendarian", provider: "Peter & Sons" },
{ name: "Bunny Heist", provider: "Peter & Sons" },
{ name: "Muddy Waters", provider: "Peter & Sons" },
{ name: "Bubblegum & Robo", provider: "Peter & Sons" },
{ name: "Blood Club", provider: "Peter & Sons" },
{ name: "Boom Farm", provider: "Peter & Sons" },
{ name: "The Legend of Musashi", provider: "Peter & Sons" },
{ name: "Book of Books", provider: "Peter & Sons" },
{ name: "Bad Santa", provider: "Peter & Sons" },
{ name: "Sheriff Colt", provider: "Peter & Sons" },
{ name: "Kaiser", provider: "Peter & Sons" },
{ name: "Rome - The Conquerors", provider: "Peter & Sons" },
{ name: "Pop Cop", provider: "Peter & Sons" },
{ name: "DCirque", provider: "Peter & Sons" },
{ name: "Monster Blox", provider: "Peter & Sons" },
{ name: "Barbarossa Dragon Empire", provider: "Peter & Sons" },

// PopiPlay
{ name: "Area 69", provider: "PopiPlay" },
{ name: "Baba Jam", provider: "PopiPlay" },
{ name: "Angry Fruits Xpress", provider: "PopiPlay" },
{ name: "Amazon City Of Gold", provider: "PopiPlay" },
{ name: "ANAKI SkyWalkers", provider: "PopiPlay" },
{ name: "Taco Hell", provider: "PopiPlay" },
{ name: "Sweet Punks", provider: "PopiPlay" },
{ name: "Bison Horizon Hold and Win", provider: "PopiPlay" },
{ name: "Store Wars", provider: "PopiPlay" },
{ name: "Guns And Dragons", provider: "PopiPlay" },
{ name: "Maxzilla", provider: "PopiPlay" },
{ name: "Detective Donut Kickback", provider: "PopiPlay" },
{ name: "Gates Of Anubis", provider: "PopiPlay" },
{ name: "Traders Fortune", provider: "PopiPlay" },
{ name: "Neon Fruits", provider: "PopiPlay" },
{ name: "Gold And Glory Hold and Win", provider: "PopiPlay" },
{ name: "Moneyscript", provider: "PopiPlay" },
{ name: "Dogmasons MegaWOOF", provider: "PopiPlay" },
{ name: "Money Mansion", provider: "PopiPlay" },
{ name: "Ruby Royal", provider: "PopiPlay" },
{ name: "Fish And Cash Arctic", provider: "PopiPlay" },
{ name: "Fruit Empire", provider: "PopiPlay" },
{ name: "Unipopcorn", provider: "PopiPlay" },
{ name: "Five Guys", provider: "PopiPlay" },
{ name: "Curse of Echnaton", provider: "PopiPlay" },
{ name: "Tik Tak Toad", provider: "PopiPlay" },
{ name: "Bubbles", provider: "PopiPlay" },
{ name: "Hanafuda", provider: "PopiPlay" },
{ name: "Double Diamond Night", provider: "PopiPlay" },
{ name: "Cash Wash", provider: "PopiPlay" },
{ name: "Ninja Frog", provider: "PopiPlay" },
{ name: "Blazing Coins Hold and Win", provider: "PopiPlay" },
{ name: "The Cipollino", provider: "PopiPlay" },
{ name: "Wild Wild Steel", provider: "PopiPlay" },
{ name: "Cultist", provider: "PopiPlay" },
{ name: "Wild Wild Bank", provider: "PopiPlay" },
{ name: "Wild Wild Gold", provider: "PopiPlay" },
{ name: "Wild Witches", provider: "PopiPlay" },
{ name: "Xperiment Gold", provider: "PopiPlay" },
{ name: "Dogmasons", provider: "PopiPlay" },
{ name: "Dream Diner", provider: "PopiPlay" },
{ name: "RoxDogs", provider: "PopiPlay" },
{ name: "Lime Time", provider: "PopiPlay" },
{ name: "Emotions", provider: "PopiPlay" },
{ name: "Sons of Monarchy", provider: "PopiPlay" },
{ name: "Cash Wash Deluxe", provider: "PopiPlay" },
{ name: "Monsters Getaway", provider: "PopiPlay" },
{ name: "Creepy Ink", provider: "PopiPlay" },
{ name: "Slotham City", provider: "PopiPlay" },
{ name: "Keys To The Sea", provider: "PopiPlay" },
{ name: "Junkrat Max", provider: "PopiPlay" },
{ name: "Fish and Cash", provider: "PopiPlay" },
{ name: "Echnaton Gold", provider: "PopiPlay" },
{ name: "Raven Bjorn", provider: "PopiPlay" },
{ name: "Tiki Trip", provider: "PopiPlay" },
{ name: "Spinguin", provider: "PopiPlay" },
{ name: "Mythos", provider: "PopiPlay" },
{ name: "Blades of Rome", provider: "PopiPlay" },
{ name: "UFO Joe", provider: "PopiPlay" },
{ name: "Veracruz Wild", provider: "PopiPlay" },
{ name: "Big Fruit Theory", provider: "PopiPlay" },
{ name: "Queen of the Nile", provider: "PopiPlay" },
{ name: "Gamba Mamba", provider: "PopiPlay" },
{ name: "Oktobearfest", provider: "PopiPlay" },
{ name: "Jellyens X", provider: "PopiPlay" },

// Pragmatic Play (Chunk 1)

{ name: "Sweet Bonanza 1000", provider: "Pragmatic Play" },
{ name: "Big Bass Splash", provider: "Pragmatic Play" },
{ name: "Gates of Olympus Super Scatter", provider: "Pragmatic Play" },
{ name: "Gates of Olympus 1000", provider: "Pragmatic Play" },
{ name: "Fire Portals", provider: "Pragmatic Play" },
{ name: "Zeus vs Hades Gods of War 250", provider: "Pragmatic Play" },
{ name: "6 Jokers", provider: "Pragmatic Play" },
{ name: "Eye of Spartacus", provider: "Pragmatic Play" },
{ name: "Starlight Princess", provider: "Pragmatic Play" },
{ name: "Big Bass Vegas Double Down Deluxe", provider: "Pragmatic Play" },
{ name: "The Dog House", provider: "Pragmatic Play" },
{ name: "Super Tiki Strike", provider: "Pragmatic Play" },
{ name: "Big Bass Reel Repeat", provider: "Pragmatic Play" },
{ name: "Fire Stampede Ultimate", provider: "Pragmatic Play" },
{ name: "3 Magic Eggs", provider: "Pragmatic Play" },
{ name: "Sugar Rush Super Scatter", provider: "Pragmatic Play" },
{ name: "Sugar Rush 1000", provider: "Pragmatic Play" },
{ name: "Zeus vs Hades Gods of War", provider: "Pragmatic Play" },
{ name: "Big Bass Splash 1000", provider: "Pragmatic Play" },
{ name: "Bigger Barn House Bonanza", provider: "Pragmatic Play" },
{ name: "Fruit Party", provider: "Pragmatic Play" },
{ name: "Floating Dragon", provider: "Pragmatic Play" },
{ name: "Witch Heart Megaways", provider: "Pragmatic Play" },
{ name: "The Dog House Dog or Alive", provider: "Pragmatic Play" },
{ name: "Sweet Rush Bonanza", provider: "Pragmatic Play" },
{ name: "Floating Dragon Wild Horses", provider: "Pragmatic Play" },
{ name: "Rolling in Treasures", provider: "Pragmatic Play" },
{ name: "Starlight Princess 1000", provider: "Pragmatic Play" },
{ name: "Haunted Crypt", provider: "Pragmatic Play" },
{ name: "Gems Bonanza", provider: "Pragmatic Play" },
{ name: "Sweet Burst", provider: "Pragmatic Play" },
{ name: "Bloody Dawn", provider: "Pragmatic Play" },
{ name: "Sugar Rush", provider: "Pragmatic Play" },
{ name: "Juicy Fruits", provider: "Pragmatic Play" },
{ name: "The Wild Machine", provider: "Pragmatic Play" },
{ name: "Gates of Hades", provider: "Pragmatic Play" },
{ name: "Resurrecting Riches", provider: "Pragmatic Play" },
{ name: "Book of Golden Sands", provider: "Pragmatic Play" },
{ name: "Bee Keeper", provider: "Pragmatic Play" },
{ name: "Waves of Poseidon", provider: "Pragmatic Play" },
{ name: "Rocket Blast Megaways", provider: "Pragmatic Play" },
{ name: "The Great Stick Up", provider: "Pragmatic Play" },
{ name: "Buffalo King Megaways", provider: "Pragmatic Play" },
{ name: "5 Lions Megaways", provider: "Pragmatic Play" },
{ name: "Hot Fiesta", provider: "Pragmatic Play" },
{ name: "Excalibur Unleashed", provider: "Pragmatic Play" },
{ name: "Cyber Heist City", provider: "Pragmatic Play" },
{ name: "Emerald King Wheel of Wealth", provider: "Pragmatic Play" },
{ name: "Lucky Tiger Gold", provider: "Pragmatic Play" },
{ name: "Big Bass Xmas Xtreme", provider: "Pragmatic Play" },
{ name: "Gates of Olympus Xmas 1000", provider: "Pragmatic Play" },
{ name: "Big Bass Boxing Bonus Round", provider: "Pragmatic Play" },
{ name: "Big Bass Secrets of the Golden Lake", provider: "Pragmatic Play" },
{ name: "Cleocatra", provider: "Pragmatic Play" },
{ name: "Sugar Rush Xmas", provider: "Pragmatic Play" },
{ name: "Sweet Bonanza", provider: "Pragmatic Play" },
{ name: "Mummy's Jewels 100", provider: "Pragmatic Play" },
{ name: "Brick House Bonanza", provider: "Pragmatic Play" },
{ name: "Sweet Bonanza Super Scatter", provider: "Pragmatic Play" },
{ name: "Hammerstorm", provider: "Pragmatic Play" },
{ name: "Pompeii Megareels Megaways", provider: "Pragmatic Play" },
{ name: "Congo Cash", provider: "Pragmatic Play" },
{ name: "Fortune of Giza", provider: "Pragmatic Play" },
{ name: "Bigger Bass Splash", provider: "Pragmatic Play" },
{ name: "The Dog House Multihold", provider: "Pragmatic Play" },
{ name: "Big Bass Day at the Races", provider: "Pragmatic Play" },
{ name: "5 Lions", provider: "Pragmatic Play" },
{ name: "Big Bass Bonanza 1000", provider: "Pragmatic Play" },
{ name: "Gorilla Mayhem", provider: "Pragmatic Play" },
{ name: "Pinup Girls", provider: "Pragmatic Play" },
{ name: "Fish Eye", provider: "Pragmatic Play" },
{ name: "Vampy Party", provider: "Pragmatic Play" },
{ name: "Gates of Olympus Dice", provider: "Pragmatic Play" },
{ name: "Master Joker", provider: "Pragmatic Play" },
{ name: "The Hand of Midas", provider: "Pragmatic Play" },
{ name: "Sweet Bonanza Xmas", provider: "Pragmatic Play" },
{ name: "Wild Bison Charge", provider: "Pragmatic Play" },
{ name: "Big Bass Halloween", provider: "Pragmatic Play" },
{ name: "Rock Vegas", provider: "Pragmatic Play" },
{ name: "Release the Bison", provider: "Pragmatic Play" },
{ name: "Wild West Gold Megaways", provider: "Pragmatic Play" },
{ name: "888 Dragons", provider: "Pragmatic Play" },
{ name: "Mighty Munching Melons", provider: "Pragmatic Play" },
{ name: "Mining Rush", provider: "Pragmatic Play" },
{ name: "Big Bass Mission Fishin", provider: "Pragmatic Play" },
{ name: "Gates of Olympus", provider: "Pragmatic Play" },
{ name: "Madame Destiny Megaways", provider: "Pragmatic Play" },
{ name: "Big Bass Christmas Bash", provider: "Pragmatic Play" },
{ name: "Buffalo King", provider: "Pragmatic Play" },
{ name: "Mystic Chief", provider: "Pragmatic Play" },
{ name: "Starlight Princess Super Scatter", provider: "Pragmatic Play" },
{ name: "Big Burger Load It Up With Extra Cheese", provider: "Pragmatic Play" },
{ name: "Vegas Magic", provider: "Pragmatic Play" },
{ name: "Big Bass Return to the Races", provider: "Pragmatic Play" },
{ name: "The Dog House Megaways", provider: "Pragmatic Play" },
{ name: "Wild Skullz", provider: "Pragmatic Play" },
{ name: "Zombie School Megaways", provider: "Pragmatic Play" },
{ name: "Release the Kraken", provider: "Pragmatic Play" },
{ name: "Big Bass Amazon Xtreme", provider: "Pragmatic Play" },
{ name: "5 Lions Reborn", provider: "Pragmatic Play" },
{ name: "Oracle of Gold", provider: "Pragmatic Play" },
{ name: "Big Bass Christmas Frozen Lake", provider: "Pragmatic Play" },
{ name: "The Dog House Muttley Crew", provider: "Pragmatic Play" },
{ name: "Gold Train", provider: "Pragmatic Play" },
{ name: "Wild West Gold Blazing Bounty", provider: "Pragmatic Play" },
{ name: "Super Gummy Strike", provider: "Pragmatic Play" },
{ name: "Genie's Gem Bonanza", provider: "Pragmatic Play" },
{ name: "Trees of Treasure", provider: "Pragmatic Play" },
{ name: "Wild West Duels", provider: "Pragmatic Play" },
{ name: "Great Rhino Megaways", provider: "Pragmatic Play" },
{ name: "Journey to the West", provider: "Pragmatic Play" },
{ name: "Starlight Christmas", provider: "Pragmatic Play" },
{ name: "Buffalo King Untamed Megaways", provider: "Pragmatic Play" },
{ name: "John Hunter and the Tomb of the Scarab Queen", provider: "Pragmatic Play" },
{ name: "Mochimon", provider: "Pragmatic Play" },
{ name: "Release the Kraken 2", provider: "Pragmatic Play" },
{ name: "Wild West Gold", provider: "Pragmatic Play" },
{ name: "Drill That Gold", provider: "Pragmatic Play" },
{ name: "Sweet Powernudge", provider: "Pragmatic Play" },
{ name: "Da Vinci's Treasure", provider: "Pragmatic Play" },
{ name: "Duel of Night and Day", provider: "Pragmatic Play" },
{ name: "Spartan King", provider: "Pragmatic Play" },
{ name: "Bigger Bass Bonanza", provider: "Pragmatic Play" },
{ name: "Sugar Supreme Powernudge", provider: "Pragmatic Play" },
{ name: "Peppes Pepperoni Pizza Plaza", provider: "Pragmatic Play" },
{ name: "3 Buzzing Wilds", provider: "Pragmatic Play" },
{ name: "Wisdom of Athena", provider: "Pragmatic Play" },
{ name: "Extra Juicy Megaways", provider: "Pragmatic Play" },
{ name: "Wheel of Happiness", provider: "Pragmatic Play" },
{ name: "Book of Monsters", provider: "Pragmatic Play" },
{ name: "Timber Stacks", provider: "Pragmatic Play" },
{ name: "Bomb Bonanza", provider: "Pragmatic Play" },
{ name: "John Hunter and the Book of Tut Respin", provider: "Pragmatic Play" },
{ name: "Floating Dragon Megaways", provider: "Pragmatic Play" },
{ name: "Frightening Frankie", provider: "Pragmatic Play" },
{ name: "Badge Blitz", provider: "Pragmatic Play" },
{ name: "Dragon Hero", provider: "Pragmatic Play" },
{ name: "Twilight Princess", provider: "Pragmatic Play" },
{ name: "John Hunter and the Book of Tut", provider: "Pragmatic Play" },
{ name: "Muertos Multiplier Megaways", provider: "Pragmatic Play" },
{ name: "Pixie Wings", provider: "Pragmatic Play" },
{ name: "Fire Archer", provider: "Pragmatic Play" },
{ name: "Mystery Mice", provider: "Pragmatic Play" },
{ name: "Sky Bounty", provider: "Pragmatic Play" },
{ name: "Zeus vs Typhon", provider: "Pragmatic Play" },
{ name: "The Wild Gang", provider: "Pragmatic Play" },
{ name: "Wild Wild Riches Megaways", provider: "Pragmatic Play" },
{ name: "Monster Superlanche", provider: "Pragmatic Play" },
{ name: "Starz Megaways", provider: "Pragmatic Play" },
{ name: "Wisdom of Athena 1000", provider: "Pragmatic Play" },
{ name: "Big Bass Floats My Boat", provider: "Pragmatic Play" },
{ name: "Mustang Gold", provider: "Pragmatic Play" },
{ name: "Panda Fortune 2", provider: "Pragmatic Play" },
{ name: "Sumo Supreme Megaways", provider: "Pragmatic Play" },
{ name: "Cowboys Gold", provider: "Pragmatic Play" },
{ name: "3 Dancing Monkeys", provider: "Pragmatic Play" },
{ name: "Club Tropicana Happy Hour", provider: "Pragmatic Play" },
{ name: "Candy Blitz", provider: "Pragmatic Play" },
{ name: "Gold Oasis", provider: "Pragmatic Play" },
{ name: "Peak Power", provider: "Pragmatic Play" },
{ name: "Candy Stars", provider: "Pragmatic Play" },
{ name: "The Money Men Megaways", provider: "Pragmatic Play" },
{ name: "Dragon Kingdom Eyes of Fire", provider: "Pragmatic Play" },
{ name: "Gold Rush", provider: "Pragmatic Play" },
{ name: "Mahjong Wins Super Scatter", provider: "Pragmatic Play" },
{ name: "Santa's Slay", provider: "Pragmatic Play" },
{ name: "Wild Spells", provider: "Pragmatic Play" },
{ name: "Piggy Bankers", provider: "Pragmatic Play" },
{ name: "Treasures of Osiris", provider: "Pragmatic Play" },
{ name: "Cash Patrol", provider: "Pragmatic Play" },
{ name: "Year of the Dragon King", provider: "Pragmatic Play" },
{ name: "Hot to Burn Extreme", provider: "Pragmatic Play" },
{ name: "Three Kingdoms", provider: "Pragmatic Play" },
{ name: "Diamond Cascade", provider: "Pragmatic Play" },
{ name: "Mummy's Jewels", provider: "Pragmatic Play" },
{ name: "Demon Pots", provider: "Pragmatic Play" },
{ name: "Sticky Bees", provider: "Pragmatic Play" },
{ name: "Dwarven Gold Deluxe", provider: "Pragmatic Play" },
{ name: "Caishen's Cash", provider: "Pragmatic Play" },
{ name: "Piggy Bank Bills", provider: "Pragmatic Play" },
{ name: "Tropical Tiki", provider: "Pragmatic Play" },
{ name: "Fruit Party 2", provider: "Pragmatic Play" },
{ name: "Aztec Gems Deluxe", provider: "Pragmatic Play" },
{ name: "Beware the Deep Megaways", provider: "Pragmatic Play" },
{ name: "Goblin Heist Powernudge", provider: "Pragmatic Play" },
{ name: "Jurassic Giants", provider: "Pragmatic Play" },
{ name: "Santa's Great Gifts", provider: "Pragmatic Play" },
{ name: "Blazing Wilds Megaways", provider: "Pragmatic Play" },
{ name: "Gods of Giza", provider: "Pragmatic Play" },
{ name: "Tic Tac Take", provider: "Pragmatic Play" },
{ name: "Zombie Carnival", provider: "Pragmatic Play" },
{ name: "Chicken Drop", provider: "Pragmatic Play" },
{ name: "Lava Balls", provider: "Pragmatic Play" },
{ name: "Penguins Christmas Party Time", provider: "Pragmatic Play" },
{ name: "The Red Queen", provider: "Pragmatic Play" },
{ name: "Floating Dragon Year of the Snake", provider: "Pragmatic Play" },
{ name: "Jewel Rush", provider: "Pragmatic Play" },
{ name: "The Great Chicken Escape", provider: "Pragmatic Play" },
{ name: "Forging Wilds", provider: "Pragmatic Play" },
{ name: "Infective Wild", provider: "Pragmatic Play" },
{ name: "Phoenix Forge", provider: "Pragmatic Play" },
{ name: "Pub Kings", provider: "Pragmatic Play" },
{ name: "Blade and Fangs", provider: "Pragmatic Play" },
{ name: "Fortunes of Aztec", provider: "Pragmatic Play" },
{ name: "Bandit Megaways", provider: "Pragmatic Play" },
{ name: "Hot Pepper", provider: "Pragmatic Play" },
{ name: "Power of Thor Megaways", provider: "Pragmatic Play" },
{ name: "Candy Corner", provider: "Pragmatic Play" },
{ name: "Fiesta Fortune", provider: "Pragmatic Play" },
{ name: "Juicy Fruits Multihold", provider: "Pragmatic Play" },
{ name: "Money Blitz", provider: "Pragmatic Play" },
{ name: "Voodoo Magic", provider: "Pragmatic Play" },
{ name: "5 Frozen Charms Megaways", provider: "Pragmatic Play" },
{ name: "Forge of Olympus", provider: "Pragmatic Play" },
{ name: "Gem Elevator", provider: "Pragmatic Play" },
{ name: "Gem Fire Fortune", provider: "Pragmatic Play" },
{ name: "Hellvis Wild", provider: "Pragmatic Play" },
{ name: "The Big Dawgs", provider: "Pragmatic Play" },
{ name: "Wild Depth", provider: "Pragmatic Play" },
{ name: "Wild Hop & Drop", provider: "Pragmatic Play" },
{ name: "5 Lions Gold", provider: "Pragmatic Play" },
{ name: "7 Clovers of Fortune", provider: "Pragmatic Play" },
{ name: "Argonauts", provider: "Pragmatic Play" },
{ name: "Aztec Powernudge", provider: "Pragmatic Play" },
{ name: "Captain Kraken Megaways", provider: "Pragmatic Play" },
{ name: "Castle of Fire", provider: "Pragmatic Play" },
{ name: "Congo Cash XL", provider: "Pragmatic Play" },
{ name: "Dragon Gold 88", provider: "Pragmatic Play" },
{ name: "Dragon Tiger Fortunes", provider: "Pragmatic Play" },
{ name: "Dynamite Diggin Doug", provider: "Pragmatic Play" },
{ name: "Emerald King Rainbow Road", provider: "Pragmatic Play" },
{ name: "Fangtastic Freespins", provider: "Pragmatic Play" },
{ name: "Fire Stampede", provider: "Pragmatic Play" },
{ name: "Gates of Valhalla", provider: "Pragmatic Play" },
{ name: "Ice Lobster", provider: "Pragmatic Play" },
{ name: "Ice Mints", provider: "Pragmatic Play" },
{ name: "Lamp of Infinity", provider: "Pragmatic Play" },
{ name: "Magic Money Maze", provider: "Pragmatic Play" },
{ name: "Might of Freya Megaways", provider: "Pragmatic Play" },
{ name: "Mysterious Egypt", provider: "Pragmatic Play" },
{ name: "Oodles of Noodles", provider: "Pragmatic Play" },
{ name: "Pot of Fortune", provider: "Pragmatic Play" },
{ name: "Power of Merlin Megaways", provider: "Pragmatic Play" },
{ name: "Rainbow Reels", provider: "Pragmatic Play" },
{ name: "Rise of Giza Powernudge", provider: "Pragmatic Play" },
{ name: "Rise of Pyramids", provider: "Pragmatic Play" },
{ name: "Santa's Xmas Rush", provider: "Pragmatic Play" },
{ name: "Temple Guardians", provider: "Pragmatic Play" },
{ name: "The Dog House Royal Hunt", provider: "Pragmatic Play" },
{ name: "The Knight King", provider: "Pragmatic Play" },
{ name: "Wild Wild Pearls", provider: "Pragmatic Play" },

// Shady Lady
{ name: "Brainwashed", provider: "Shady Lady" },
{ name: "Orphan Organ", provider: "Shady Lady" },
{ name: "Laced", provider: "Shady Lady" },
{ name: "Swoll", provider: "Shady Lady" },
{ name: "Devil's Finger", provider: "Shady Lady" },
{ name: "Oops", provider: "Shady Lady" },
{ name: "Suck", provider: "Shady Lady" },
{ name: "Office Party", provider: "Shady Lady" },
{ name: "Sew", provider: "Shady Lady" },
{ name: "Black Friday", provider: "Shady Lady" },
];

export const providerLogos: Record<string, string> = {
  "Backseat Gaming": "https://usercontent.cc/logos/providers/white/backseatgaming.svg",
  "3 Oaks": "https://usercontent.cc/logos/providers/white/3oaks.svg",
  AvatarUX: "https://usercontent.cc/logos/providers/white/avatarux.svg",
  BGaming: "https://usercontent.cc/logos/providers/white/bgaming.svg",
  Bullshark: "/providers/bullshark.png",
  Clawbuster: "https://usercontent.cc/logos/providers/white/clawbuster.svg",
  "Hacksaw Gaming": "https://usercontent.cc/logos/providers/white/hacksaw.svg",
  "Peter & Sons": "https://usercontent.cc/logos/providers/white/petersons.svg",
  Popiplay: "https://usercontent.cc/logos/providers/white/popiplay.svg",
  "Shady Lady": "https://usercontent.cc/logos/providers/white/shadylady.svg",
  "Pragmatic Play": "https://usercontent.cc/logos/providers/white/pragmaticplay.svg",
};