const fs=require("fs"),assert=require("node:assert/strict"),ts=require("typescript"),vm=require("node:vm");
function moduleAt(path){const js=ts.transpileModule(fs.readFileSync(path,"utf8"),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;const exports={};vm.runInNewContext(js,{exports,require,Map,Set,BigInt,URL,AbortSignal,fetch});return exports;}
const match=moduleAt("lib/slot-matching.ts"),math=moduleAt("lib/tracker-math.ts"),art=moduleAt("lib/roulo-artwork.ts");
const games=[{identifier:"hacksaw:wanted",name:"Wanted Dead or a Wild",provider:"hacksaw",artwork_url:null,aliases:["wanted"]},{identifier:"hacksaw:chaos",name:"Chaos Crew 2",provider:"hacksaw",artwork_url:null}];
assert.equal(match.matchSlot("wanted",games).game.identifier,"hacksaw:wanted");assert.equal(match.matchSlot("WANTED DEAD OR A WILD",games).status,"matched");assert.equal(match.matchSlot("Wanted Dead or a Wil",games).status,"matched");assert.equal(match.matchSlot("x",games).status,"review");assert.equal(match.matchSlot("Chaos Crew",[...games,{...games[1],identifier:"other:chaos"}]).status,"review");assert.equal(match.matchSlot("wanted",[{...games[0],enabled:false}]).status,"review");
assert.equal(match.matchSlot("Wanted Dead or a Wild",[games[0],{...games[0],identifier:"hacksawg:wanted",provider:"hacksawg"}]).status,"matched");
const providers=moduleAt("lib/slot-providers.ts");assert.equal(providers.FEATURED_PROVIDERS.length,10);assert.equal(providers.providerName("hacksawg","backseatgaming"),"Backseat Gaming");assert.equal(providers.providerName("evolution","netent"),"NetEnt");assert.equal(providers.providerName("bgmng"),"BGaming");assert.equal(providers.providerName("spnmnl"),"Spinomenal");
const stats=math.trackerStats("100",[{status:"collected",bet_size:"0.20",payout:"10",collection_cost:"20"},{status:"collected",bet_size:"0.50",payout:null,collection_cost:"30"},{status:"failed",bet_size:"0.20",payout:null,collection_cost:"5"}]);assert.equal(stats.averagePayoutRequired,180);assert.equal(stats.currentAverageMultiplier,50);assert.equal(stats.profitLoss,-90);assert.equal(stats.collectionCosts,55);assert.equal(stats.openedBonuses,1);assert.equal(math.trackerStats("0",[]).averagePayoutRequired,0);assert.equal(math.trackerStats("100",[]).averagePayoutRequired,null);assert.equal(math.money("0.123456"),BigInt(123456));assert.throws(()=>math.money("-1"));
const source='229436:(e,t,a)=>{var s={"./hacksaw/Wanted.webp":123};123:(e,t,a)=>{"use strict";e.exports=a.p+"static/media/Wanted.abc.webp"}';const index=art.artworkIndex(source);assert.equal(art.findArtwork(index,{identifier:"hacksawg:Wanted",provider:"hacksawg"}),"https://roulobets.com/static/media/Wanted.abc.webp");assert.equal(art.findArtwork(index,{identifier:"other:Wanted",provider:"other"}),null);assert.throws(()=>art.artworkIndex("changed-source"));console.log("PASS exact/alias/typo matching, ambiguity/disabled guards, weighted remaining average, precise money, source artwork mapping and format-change rejection");

const nut={identifier:"n2games:NutJob",name:"Nut Job",provider:"n2games",artwork_url:null};assert.equal(match.matchSlot("ntu job",[nut,...games]).game.identifier,nut.identifier);assert.equal(match.matchSlot("nut",[nut,...games]).status,"review");assert.equal(match.matchSlot("ntu job",[nut,{...nut,identifier:"other:NutJob"}]).status,"review");assert.equal(match.matchSlot("unknown mystery slot",[nut,...games]).status,"review");
